#!/usr/bin/env python3
"""
Reference Analyzer - Refinery Subsystem for Academic Library Processing
=========================================================================

Handles systematic processing of the reference library:
1. Analyze remaining 56 refs (batch LLM analysis)
2. Build full-text search index
3. Optimize caption extraction (filter artifacts)
4. Extract holon hierarchies

Integrates with Refinery subsystem architecture.
"""

import json
from pathlib import Path
from typing import Dict, List, Optional
from dataclasses import dataclass
from datetime import datetime

# Paths
REFINERY_DIR = Path(__file__).parent
REFS_DIR = REFINERY_DIR.parent.parent / "archive/references"
PROJECT_ROOT = REFINERY_DIR.parent.parent.parent


@dataclass
class AnalysisJob:
    """A reference analysis job."""
    ref_id: str
    priority_tier: int
    status: str  # pending, processing, complete, failed
    created: str
    completed: Optional[str] = None
    error: Optional[str] = None


class ReferenceAnalyzer:
    """Systematic reference library processor."""

    def __init__(self):
        self.refs_dir = REFS_DIR
        self.metadata_dir = self.refs_dir / "metadata"
        self.txt_dir = self.refs_dir / "txt"
        self.index_dir = self.refs_dir / "index"

    def scan_pending_analyses(self) -> List[str]:
        """Find all refs with stub metadata (need LLM analysis)."""
        pending = []

        for meta_file in self.metadata_dir.glob("*.json"):
            if "_analysis" in meta_file.name:
                continue

            try:
                meta = json.loads(meta_file.read_text())
                summary = meta.get("summary", "")

                if summary == "[TO BE GENERATED BY LLM]" or len(summary) < 100:
                    pending.append(meta["ref_id"])
            except:
                pass

        return sorted(pending)

    def prioritize_refs(self, ref_ids: List[str]) -> Dict[int, List[str]]:
        """Group refs by priority tier."""
        tiers = {1: [], 2: [], 3: [], 4: []}

        for ref_id in ref_ids:
            meta_file = self.metadata_dir / f"{ref_id}.json"
            if not meta_file.exists():
                continue

            try:
                meta = json.loads(meta_file.read_text())
                tier = meta.get("priority_tier", 4)
                tiers.get(tier, tiers[4]).append(ref_id)
            except:
                tiers[4].append(ref_id)

        return tiers

    def build_fulltext_index(self) -> Dict[str, List[str]]:
        """
        Build full-text search index: term → [ref_ids].

        Returns index mapping terms to references containing them.
        """
        index = {}

        # Index metadata
        for meta_file in self.metadata_dir.glob("*.json"):
            if "_analysis" in meta_file.name:
                continue

            try:
                meta = json.loads(meta_file.read_text())
                ref_id = meta["ref_id"]

                # Index title words
                for word in meta.get("title", "").lower().split():
                    if len(word) > 3:
                        index.setdefault(word, []).append(ref_id)

                # Index authors
                for author in meta.get("authors", []):
                    for word in author.lower().split():
                        if len(word) > 2:
                            index.setdefault(word, []).append(ref_id)

                # Index SMoC concepts
                for concept_mapping in meta.get("key_smoc_concepts", []):
                    concept = concept_mapping.get("smoc_concept", "")
                    if concept:
                        index.setdefault(concept, []).append(ref_id)

            except:
                pass

        # Deduplicate
        for term in index:
            index[term] = sorted(list(set(index[term])))

        return index

    def save_fulltext_index(self):
        """Build and save full-text search index."""
        index = self.build_fulltext_index()

        output_file = self.index_dir / "search_index.json"
        output_file.write_text(json.dumps(index, indent=2))

        print(f"✓ Full-text index built: {len(index):,} terms")
        print(f"  Saved to: {output_file}")

        return index

    def filter_image_artifacts(self, ref_id: str) -> Dict[str, int]:
        """
        Filter PDF artifacts from images, keep only content figures.

        Returns stats: total, artifacts, content.
        """
        img_dir = self.refs_dir / "images" / ref_id
        if not img_dir.exists():
            return {"total": 0, "artifacts": 0, "content": 0}

        meta_file = img_dir / "metadata.json"
        if not meta_file.exists():
            return {"total": 0, "artifacts": 0, "content": 0}

        meta = json.loads(meta_file.read_text())
        figures = meta.get("figures", [])

        artifacts = 0
        content = 0

        for fig in figures:
            w = fig.get("width", 0)
            h = fig.get("height", 0)
            size = fig.get("size_bytes", 0)

            # Classify as artifact if:
            aspect = max(w, h) / max(min(w, h), 1) if min(w, h) > 0 else 1

            if aspect > 20:  # Very thin line
                artifacts += 1
            elif min(w, h) < 50:  # Very narrow
                artifacts += 1
            elif size < 2000:  # Tiny file
                artifacts += 1
            else:
                content += 1

        return {
            "total": len(figures),
            "artifacts": artifacts,
            "content": content,
            "ref_id": ref_id
        }

    def generate_analysis_batch(self, ref_ids: List[str], output_file: Path):
        """
        Generate batch analysis request for multiple refs.

        Creates a JSON file for batch processing via LLM API.
        """
        batch_requests = []

        for ref_id in ref_ids:
            txt_file = self.txt_dir / f"{ref_id}.txt"
            if not txt_file.exists():
                continue

            # Load text (first 50K chars for analysis)
            text = txt_file.read_text(encoding="utf-8", errors="ignore")[:50000]

            batch_requests.append({
                "ref_id": ref_id,
                "text_sample": text,
                "instruction": "Analyze this academic work for SMoC relevance. Generate JSON with: summary, smoc_relevance_summary, key_smoc_concepts, important_equations, cross_references, priority_tier."
            })

        output_file.write_text(json.dumps(batch_requests, indent=2))

        print(f"✓ Batch analysis file created: {output_file}")
        print(f"  Refs: {len(batch_requests)}")
        print(f"  Next: Feed to LLM batch API")

    def status_report(self) -> Dict:
        """Generate complete status report."""
        pending = self.scan_pending_analyses()
        tiers = self.prioritize_refs(pending)

        return {
            "total_refs": len(list(self.metadata_dir.glob("*.json"))) - len(list(self.metadata_dir.glob("*_analysis.json"))),
            "analyzed": len(list(self.metadata_dir.glob("*.json"))) - len(pending) - len(list(self.metadata_dir.glob("*_analysis.json"))),
            "pending": len(pending),
            "by_priority": {
                f"Tier {tier}": len(refs) for tier, refs in tiers.items() if refs
            },
            "indexes": {
                "catalog": (self.index_dir / "catalog.json").exists(),
                "concepts": (self.index_dir / "concept_index.json").exists(),
                "fulltext": (self.index_dir / "search_index.json").exists()
            }
        }


def cmd_status():
    """Show reference analyzer status."""
    analyzer = ReferenceAnalyzer()
    status = analyzer.status_report()

    print("=== REFERENCE ANALYZER STATUS ===")
    print(f"Total refs:  {status['total_refs']}")
    print(f"Analyzed:    {status['analyzed']}")
    print(f"Pending:     {status['pending']}")
    print()
    print("By priority:")
    for tier, count in status['by_priority'].items():
        print(f"  {tier}: {count}")
    print()
    print("Indexes:")
    for idx_name, exists in status['indexes'].items():
        status_str = "✓" if exists else "✗"
        print(f"  {status_str} {idx_name}")


def cmd_build_index():
    """Build full-text search index."""
    analyzer = ReferenceAnalyzer()
    analyzer.save_fulltext_index()


def cmd_filter_artifacts():
    """Analyze and report on image artifacts."""
    analyzer = ReferenceAnalyzer()

    print("=== IMAGE ARTIFACT ANALYSIS ===")
    print()

    total_all = 0
    total_artifacts = 0
    total_content = 0

    for img_dir in sorted((analyzer.refs_dir / "images").iterdir()):
        if not img_dir.is_dir():
            continue

        stats = analyzer.filter_image_artifacts(img_dir.name)
        if stats["total"] > 0:
            total_all += stats["total"]
            total_artifacts += stats["artifacts"]
            total_content += stats["content"]

            pct = 100 * stats["content"] / stats["total"]
            if pct < 50:
                print(f"⚠️ {stats['ref_id']}: {stats['content']}/{stats['total']} content ({pct:.0f}%)")

    print()
    print(f"TOTAL: {total_content:,} content / {total_all:,} total ({100*total_content/total_all:.1f}%)")
    print(f"Artifacts: {total_artifacts:,} ({100*total_artifacts/total_all:.1f}%)")


def cmd_batch_prepare(tier: int = 2):
    """Prepare batch analysis file for a priority tier."""
    analyzer = ReferenceAnalyzer()
    pending = analyzer.scan_pending_analyses()
    tiers = analyzer.prioritize_refs(pending)

    refs_to_analyze = tiers.get(tier, [])

    if not refs_to_analyze:
        print(f"No pending Tier {tier} refs")
        return

    output_file = analyzer.refs_dir / f"batch_tier{tier}_analysis.json"
    analyzer.generate_analysis_batch(refs_to_analyze, output_file)


def main():
    import sys

    if len(sys.argv) < 2:
        print("Usage: python3 reference_analyzer.py <command>")
        print()
        print("Commands:")
        print("  status            - Show analysis status")
        print("  build-index       - Build full-text search index")
        print("  filter-artifacts  - Analyze image artifact ratio")
        print("  batch-prepare <tier> - Prepare batch analysis file")
        return

    cmd = sys.argv[1]

    if cmd == "status":
        cmd_status()
    elif cmd == "build-index":
        cmd_build_index()
    elif cmd == "filter-artifacts":
        cmd_filter_artifacts()
    elif cmd == "batch-prepare":
        tier = int(sys.argv[2]) if len(sys.argv) > 2 else 2
        cmd_batch_prepare(tier)
    else:
        print(f"Unknown command: {cmd}")


if __name__ == "__main__":
    main()
