"""Finance tools: Pluggy, invoices, bank flows, confirmations."""

from tool_registry import ToolSpec, registry

TOOLS = [
    ToolSpec(
        name="finance_status",
        description="Check finance bridge health, Pluggy/Binance config, and pending confirmations.",
        parameters={"type": "object", "properties": {}},
        method="GET",
        path="/api/voice/finance/status",
        source="elevenlabs",
        tags=["finance"],
    ),
    ToolSpec(
        name="finance_snapshot",
        description="Aggregate realtime balances and transaction flow across connected Pluggy items.",
        parameters={"type": "object", "properties": {}},
        method="GET",
        path="/api/voice/finance/snapshot",
        source="elevenlabs",
        max_chars=4000,
        tags=["finance"],
    ),
    ToolSpec(
        name="finance_pending_actions",
        description="List pending finance confirmations waiting for explicit confirm/cancel.",
        parameters={"type": "object", "properties": {}},
        method="GET",
        path="/api/voice/finance/pending",
        source="elevenlabs",
        tags=["finance"],
    ),
    ToolSpec(
        name="finance_confirm_action",
        description="Confirm and execute a staged finance action.",
        parameters={
            "type": "object",
            "properties": {
                "confirmation_id": {"type": "string", "description": "Action ID to confirm"},
            },
            "required": ["confirmation_id"],
        },
        method="POST",
        path="/api/voice/finance/confirm",
        source="elevenlabs",
        tags=["finance"],
    ),
    ToolSpec(
        name="finance_cancel_action",
        description="Cancel a staged finance action.",
        parameters={
            "type": "object",
            "properties": {
                "confirmation_id": {"type": "string", "description": "Action ID to cancel"},
            },
            "required": ["confirmation_id"],
        },
        method="POST",
        path="/api/voice/finance/cancel",
        source="elevenlabs",
        tags=["finance"],
    ),
    ToolSpec(
        name="bank_to_binance_flow",
        description="Prepare/execute bank-to-binance flow. payload can be JSON string.",
        parameters={"type": "object", "properties": {}},
        method="POST",
        path="/api/voice/finance/flow/bank-to-binance",
        source="elevenlabs",
        tags=["finance"],
    ),
    ToolSpec(
        name="binance_to_bank_flow",
        description="Prepare/execute binance-to-bank flow. payload can be JSON string.",
        parameters={"type": "object", "properties": {}},
        method="POST",
        path="/api/voice/finance/flow/binance-to-bank",
        source="elevenlabs",
        tags=["finance"],
    ),
    ToolSpec(
        name="check_invoices",
        description="Check pending invoices and boletos with amounts vendors and due dates.",
        parameters={"type": "object", "properties": {}},
        method="GET",
        path="/api/voice/invoices/check",
        source="elevenlabs",
        tags=["finance"],
    ),
    ToolSpec(
        name="invoice_summary",
        description="Monthly invoice summary with total and category breakdown.",
        parameters={"type": "object", "properties": {}},
        method="GET",
        path="/api/voice/invoices/summary",
        source="elevenlabs",
        tags=["finance"],
    ),
    # --- Pluggy (Open Finance BR) ---
    ToolSpec(
        name="pluggy_connect_start",
        description="Create a Pluggy Connect token/URL. options can be JSON string.",
        parameters={"type": "object", "properties": {}},
        method="POST",
        path="/api/voice/finance/pluggy/connect/start",
        source="elevenlabs",
        tags=["finance", "pluggy"],
    ),
    ToolSpec(
        name="pluggy_known_items",
        description="List known Pluggy item IDs recovered from configured sources.",
        parameters={"type": "object", "properties": {}},
        method="GET",
        path="/api/voice/finance/pluggy/items/known",
        source="elevenlabs",
        tags=["finance", "pluggy"],
    ),
    ToolSpec(
        name="pluggy_operations",
        description="List available Pluggy operations and tags.",
        parameters={"type": "object", "properties": {}},
        method="GET",
        path="/api/voice/finance/pluggy/operations",
        source="elevenlabs",
        tags=["finance", "pluggy"],
    ),
    ToolSpec(
        name="pluggy_probe_items",
        description="Probe item connectivity. Pass item_ids as JSON array string or comma-separated string.",
        parameters={"type": "object", "properties": {}},
        method="POST",
        path="/api/voice/finance/pluggy/items/probe",
        source="elevenlabs",
        tags=["finance", "pluggy"],
    ),
    ToolSpec(
        name="pluggy_refresh_item",
        description="Trigger sync refresh for a specific Pluggy item.",
        parameters={
            "type": "object",
            "properties": {
                "item_id": {"type": "string", "description": "Pluggy item ID"},
            },
            "required": ["item_id"],
        },
        method="POST",
        path="/api/voice/finance/pluggy/item/refresh",
        source="elevenlabs",
        tags=["finance", "pluggy"],
    ),
    ToolSpec(
        name="pluggy_refresh_items",
        description="Refresh multiple Pluggy items. item_ids accepts JSON array string or comma-separated ids.",
        parameters={"type": "object", "properties": {}},
        method="POST",
        path="/api/voice/finance/pluggy/items/refresh",
        source="elevenlabs",
        tags=["finance", "pluggy"],
    ),
    ToolSpec(
        name="pluggy_run_operation",
        description="Run a Pluggy operation. For complex parameters, pass JSON strings in path_params/query/body/headers.",
        parameters={
            "type": "object",
            "properties": {
                "operation_id": {"type": "string", "description": "Operation ID"},
            },
            "required": ["operation_id"],
        },
        method="POST",
        path="/api/voice/finance/pluggy/run",
        source="elevenlabs",
        tags=["finance", "pluggy"],
    ),
    ToolSpec(
        name="pluggy_submit_mfa",
        description="Submit MFA payload to Pluggy item. payload can be JSON string.",
        parameters={
            "type": "object",
            "properties": {
                "item_id": {"type": "string", "description": "Pluggy item ID"},
            },
            "required": ["item_id"],
        },
        method="POST",
        path="/api/voice/finance/pluggy/item/mfa",
        source="elevenlabs",
        tags=["finance", "pluggy"],
    ),
]

registry.register_many(TOOLS)
